version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "medical-record"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vkieeapmlspr"
s3_prefix = "medical-record"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
